services:
  - type: web
    name: virail-combined-docker
    env: docker
    envVars:
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false


