services:
  - type: web
    name: virail-combined-service
    env: python
    buildCommand: "./render-combined-build.sh"
    startCommand: "./render-combined-start.sh"
    envVars:
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false

